import Link from 'next/link';
import Nav from '@/components/Nav';
import StoleScene from '@/components/StoleScene';
import { ArrowDown,ArrowUpRight,MoveUpRight } from 'lucide-react';
const design={baseColor:'#e6d0a1',trimColor:'#75633c',style:'royal',elements:[{id:'hero-1',type:'text',side:'left',text:'CLASS OF 2026',x:49,y:38,size:17,color:'#473b2b',font:'serif',rotation:-90},{id:'hero-2',type:'text',side:'right',text:'MAKE YOUR MARK',x:51,y:40,size:16,color:'#473b2b',font:'serif',rotation:90},{id:'hero-3',type:'symbol',side:'left',text:'✦',x:50,y:75,size:33,color:'#6f5d35',rotation:0},{id:'hero-4',type:'symbol',side:'right',text:'✦',x:50,y:75,size:33,color:'#6f5d35',rotation:0}]};
const moments=[{n:'01',title:'The first idea',body:'A name. A date. A symbol only you understand. Start with what matters most.'},{n:'02',title:'Made by you',body:'Choose your palette, place every detail, and see it take shape in real time.'},{n:'03',title:'Made real by us',body:'Send your design. We review it with you, then create the piece for your day.'}];
export default function Home(){return <><Nav/><main className="editorial-page"><section className="campaign-hero"><div className="campaign-copy"><div className="campaign-kicker"><span>EST. FOR YOUR MOMENT</span><span>THE CLASS OF 2026</span></div><div className="campaign-title"><p className="campaign-overline">FOR ALL THE MOMENTS THAT BROUGHT YOU HERE</p><h1>THIS IS<br/>YOUR <i>moment.</i></h1><div className="campaign-title-footer"><span className="asterisk">✳</span><p>Your journey deserves<br/>more than a borrowed tradition.</p></div></div><div className="campaign-actions"><Link href="/design" className="campaign-button">DESIGN YOUR STOLE <ArrowUpRight size={20}/></Link><a href="#collection" className="campaign-explore">EXPLORE THE STORY <ArrowDown size={18}/></a></div><div className="campaign-footer"><span>INDIVIDUALLY DESIGNED. THOUGHTFULLY MADE.</span><span>01 — 04</span></div></div><div className="campaign-visual"><span className="visual-caption top">THE STOLE / REIMAGINED</span><div className="visual-frame"><StoleScene design={design} hero/></div><div className="visual-bottom"><span className="visual-index">A PERSONAL<br/>PIECE OF HISTORY.</span><span className="visual-sun">✺</span></div></div></section>
<div className="ticker" aria-hidden="true"><span>MADE FOR THE WALK</span><span>✳</span><span>MADE FOR THE WORK</span><span>✳</span><span>MADE FOR WHAT’S NEXT</span><span>✳</span><span>MADE FOR YOU</span><span>✳</span></div>
<section id="collection" className="collection-section"><div className="collection-head"><div><span className="section-number">01 / THE STUDIO</span><h2>A canvas for<br/><i>everything you are.</i></h2></div><div><p>Your stole is a record of the names, places and ambitions that shaped the journey. Make room for all of it.</p><Link href="/design" className="underlink">START CREATING <ArrowUpRight size={16}/></Link></div></div><div className="collection-grid"><div className="collection-large"><div className="collection-illustration"><span className="collection-stole one"/><span className="collection-stole two"/><span className="collection-stole three"/></div><span className="collection-label">01 — FORM & COLOUR</span><h3>Begin with a feeling.</h3><p>Choose the fabric, the finish and the color story.</p></div><div className="collection-small"><div className="type-study"><span>01</span><strong>THE<br/>FUTURE<br/><i>IS OURS.</i></strong><span className="type-star">✳</span></div><span className="collection-label">02 — THE DETAILS</span><h3>Say it your way.</h3><p>Names, dates, symbols, your own artwork. Every detail belongs to your story.</p></div></div></section>
<section id="craft" className="craft-section"><div className="craft-intro"><span className="section-number">02 / THE PROCESS</span><h2>Keep the magic.<br/><i>Lose the hassle.</i></h2><p>Three considered steps between the idea in your head and the stole on your shoulders.</p></div><div className="craft-steps">{moments.map(m=><article key={m.n}><span className="craft-number">{m.n}</span><div className="craft-content"><h3>{m.title}</h3><p>{m.body}</p></div><MoveUpRight size={22}/></article>)}</div></section>
<section id="about" className="statement-section"><div className="statement-rule"><span>AN INVITATION TO BE SEEN</span><span>STOLE STUDIO · 2026</span></div><div className="statement-content"><span className="statement-asterisk">✳</span><h2>You did the work.<br/>Now <i>wear the story.</i></h2><p>Not another off-the-shelf keepsake. A piece that speaks to where you’ve been and where you’re going next.</p><Link href="/design" className="statement-button">ENTER THE STUDIO <ArrowUpRight size={23}/></Link></div></section></main><footer className="editorial-footer"><div className="footer-brand">STOLE<br/>STUDIO<span>✳</span></div><div className="footer-meta"><p>Designed by you. Made for your moment.</p><div><Link href="/design">Design your stole</Link><Link href="/admin">Team access</Link></div><small>© {new Date().getFullYear()} STOLE STUDIO. ALL RIGHTS RESERVED.</small></div></footer></>}
